services:
  prefect-server:
    image: prefecthq/prefect:3.0.0rc14-python3.11
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    ports:
      - "4200:4200"
    networks:
      - prefect-network

  prefect-worker:
    image: prefecthq/prefect:3.0.0rc14-python3.11
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    networks:
      - prefect-network

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    networks:
      - prefect-network

networks:
  prefect-network:
    driver: bridge