[project]
name = "tastetester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=6.31.0",
    "musicbrainzngs>=0.7.1",
    "numpy>=2.0.2",
    "optuna>=4.6.0",
    "optuna-integration[xgboost]>=4.9.0",
    "pandas>=2.3.3",
    "prefect>=3.4.25",
    "pyarrow>=21.0.0",
    "pydantic>=2.12.5",
    "ratelimit>=2.2.1",
    "requests>=2.32.5",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "sqlean-py>=3.50.4.5",
    "sqlite-vec>=0.1.9",
    "statsmodels>=0.14.6",
    "streamlit>=1.50.0",
    "xgboost>=2.1.4",
]
